name: 'youtube_analytics_source'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  youtube_analytics_source:
    channel_basic: "{{ source('youtube_analytics','channel_basic') }}"
    channel_demographics: "{{ source('youtube_analytics','channel_demographics') }}"
    video_metadata: "{{ source('youtube_metadata','videos') }}"

models:
  youtube_analytics_source:
    +materialized: table
    +schema: stg_youtube
    tmp:
      +materialized: view
