name: 'youtube_analytics_source'
version: '0.5.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  youtube_analytics_source:
    channel_basic: "{{ source('youtube_analytics','channel_basic_a_2') }}"
    channel_demographics: "{{ source('youtube_analytics','channel_demographics_a_1') }}"
    video: "{{ source('youtube_analytics','video') }}"

models:
  youtube_analytics_source:
    +materialized: table
    +schema: youtube_source
    tmp:
      +materialized: view
