name: 'youtube_analytics_integration_tests'
version: '0.3.0'
profile: 'integration_tests'
config-version: 2

vars:
  youtube_analytics_source:
    channel_basic:        "{{ ref('youtube_channel_basic_data') }}"
    channel_demographics: "{{ ref('youtube_channel_demographics_data') }}"
    video_metadata:       "{{ ref('youtube_video_metadata_data') }}"
  youtube__using_video_metadata: true

seeds:
  youtube_analytics_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    youtube_channel_basic_data:
      +column_types:
        annotation_click_through_rate: "{{ 'float64' if target.type == 'bigquery' else 'float' }}"
        annotation_close_rate: "{{ 'float64' if target.type == 'bigquery' else 'float' }}"
        average_view_duration_percentage: "{{ 'float64' if target.type == 'bigquery' else 'float' }}"
        average_view_duration_seconds: "{{ 'float64' if target.type == 'bigquery' else 'float' }}"
        card_click_rate: "{{ 'float64' if target.type == 'bigquery' else 'float' }}"
        card_teaser_click_rate: "{{ 'float64' if target.type == 'bigquery' else 'float' }}"
        red_watch_time_minutes: "{{ 'float64' if target.type == 'bigquery' else 'float' }}"
        watch_time_minutes:  "{{ 'float64' if target.type == 'bigquery' else 'float' }}"
